Repository AY2122S1-CS2103T-F11-3/tp, pull requests merged in 2021-11, with the labels that each got.

#185 Update UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: UI

#191 Fix -0 input for numerical fields
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/HoursWorked.java
  src/main/java/seedu/address/model/person/LeaveBalance.java
  src/main/java/seedu/address/model/person/Overtime.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/person/HourlySalaryTest.java
  src/test/java/seedu/address/model/person/HoursWorkedTest.java
  src/test/java/seedu/address/model/person/LeaveBalanceTest.java
Labels: priority.MEDIUM, FunctionalityBug

#186 PE-D Bug Fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateEmailException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePhoneException.java
  src/test/data/CsvImportTest/DuplicateEmails.csv
  src/test/data/CsvImportTest/DuplicatePersons.csv
  src/test/data/CsvImportTest/DuplicatePhoneNumbers.csv
  src/test/data/CsvImportTest/WrongHeaders.csv
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: FunctionalityBug

#190 Fix display content when employee list empty
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ObservablePerson.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiObserver.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: priority.MEDIUM, UI

#189 Find command bugs v1.4
  docs/team/beefham.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: FunctionalityBug

#110 Update description under import feature
  docs/UserGuide.md
Labels: documentation

#188 User Guide v1.4
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addExample.png
  docs/images/findAlexDavidResult.png
  docs/images/findCarlElleResult.png
  docs/images/missingFieldImport.png
  docs/images/multipleTagImport.png
  docs/images/pay_afterPaying.png
  docs/images/pay_beforePaying.png
  docs/images/setOvertimePayRate_error.png
  docs/images/setOvertimePayRate_success.png
  docs/images/startPayrollError_unpaidEmployee.png
  docs/images/startPayroll_after.png
  docs/images/startPayroll_before.png
  docs/images/viewOvertimePayRate.png
Labels: documentation

#103 Update Developer Guide with Import Feature
  docs/DeveloperGuide.md
  docs/diagrams/ImportActivityDiagram.puml
  docs/diagrams/ImportProcessData.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/ImportUpdateGUI.puml
  docs/images/ImportActivityDiagram.png
  docs/images/ImportProcessData.png
  docs/images/ImportSequenceDiagram.png
  docs/images/ImportUpdateGUI.png
Labels: documentation

#95 Update find command in developer's guide
  docs/DeveloperGuide.md
  docs/diagrams/CombinedPredicate.puml
  docs/diagrams/FindCommandGetPredicateDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/CombinedPredicateExample.png
  docs/images/FindCommandGetPredicateDiagram.png
  docs/images/FindSequenceDiagram.png
Labels: documentation
